return PlaceObj('ModDef', {
	'title', "Recoloured Colonist Arrow Icons",
	'description', "This mod changes the colours of Colonist Arrow icons to more distinctive colours.\n\nSpecial Thanks to:\nThe Surviving Mars Modders Discord for Modding Support",
	'image', "Preview.PNG",
	'last_changes', "v2.0 Reduced filesize of fallback textures",
	'id', "RD_RCAI",
	'steam_id', "1660461805",
	'pops_desktop_uuid', "bcc34c8b-0a76-4f1c-aac3-f415edc8f321",
	'pops_any_uuid', "0a0a1531-fa49-4ed6-ad5c-bda9292a40f9",
	'author', "RustyDios",
	'version', 9,
	'lua_revision', 233360,
	'saved_with_revision', 240905,
	'code', {"Code/Script.lua"},
	'saved', 1552237924,
	'screenshot1', "Preview.PNG",
	'screenshot2', "Preview_smls.PNG",
	'TagCosmetics', true,
	'TagInterface', true,
	'TagOther', true,
})